book_repo: project-geode/geode-book
public_host: localhost

dita_sections:
- repository:
    name: project-geode/docs
  directory: docs
  ditamap_location: Geode.ditamap

template_variables:
  support_url: http://support.pivotal.io
  product_url: http://pivotal.io/big-data/pivotal-gemfire
  book_title: Project Geode Documentation
