book_repo: project-geode/geode-book
public_host: localhost

dita_sections:
- repository:
    name: project-geode/docs
  directory: docs
  ditamap_location: Geode.ditamap
  subnav_template: geode_subnav.erb

template_variables:
  support_url: http://project-geode.github.io/docs/community/
  product_url: http://project-geode.github.io/docs/
  book_title: Project Geode Documentation
